name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "0.115.1"
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          cname: blog.tyage.net

      - name: Send webmention
        uses: actions/setup-node@v3
      - run: git clone https://github.com/${GITHUB_REPOSITORY} --depth=2 --branch=gh-pages gh-pages
      - run: sleep 60 # Wait until Netlify will update content
      - run: node ../.github/workflows/notify-fed-bridgy.js
        working-directory: ./gh-pages
