name: resend webmentions

on:
  schedule:
    - cron:  '0 * * * *'

jobs:
  send:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      working-directory: ./scripts
    - run: node webmention.js
      working-directory: ./scripts
