name: resend webmentions

on:
  schedule:
    - cron:  '0 */4 * * *'

jobs:
  send:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./scripts

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
    - run: npm install
    - run: node webmention.js
